[project]
name = "cvtk"
version = "0.2.0"
description = "Computer Vision ToolKit"
readme = "README.md"
authors = [
    { name = "Maksim Shushkevich", email = "meshushkevich@edu.hse.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "nodeflow",
    "pillow>=11.1.0",
    "shapely>=2.1.0",
    "toml>=0.10.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
nodeflow = { git = "https://github.com/encore-ecosystem/NodeFlow" }
